# Generated by Django 2.2 on 2019-04-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type_name', models.CharField(max_length=100)),
                ('creadedOn', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
