# Generated by Django 2.2 on 2019-04-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0004_auto_20190430_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_type',
            name='doc_type_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
