# Generated by Django 2.2 on 2019-05-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0006_auto_20190502_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internal_audit_report',
            old_name='area_of_audit',
            new_name='areaofaudit',
        ),
    ]
