# Generated by Django 2.2 on 2019-04-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='skillmatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depaertment', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('empId', models.CharField(blank=True, max_length=50)),
                ('empName', models.CharField(blank=True, max_length=75)),
                ('drawing_studying_skills', models.CharField(blank=True, max_length=75)),
                ('usage_of_general_gauges', models.CharField(blank=True, max_length=75)),
                ('usage_of_general_instruments', models.CharField(blank=True, max_length=75)),
                ('usage_of_product_specific_gauges', models.CharField(blank=True, max_length=75)),
                ('quality_documentation', models.CharField(blank=True, max_length=75)),
                ('cmm_operating', models.CharField(blank=True, max_length=75)),
                ('pp_operating', models.CharField(blank=True, max_length=75)),
                ('operating_surface_roughness_tester', models.CharField(blank=True, max_length=75)),
                ('basic_machining_knowledge', models.CharField(blank=True, max_length=75)),
                ('microscope_handeling', models.CharField(blank=True, max_length=75)),
                ('internal_verification_skills', models.CharField(blank=True, max_length=75)),
                ('inspection_skill', models.CharField(blank=True, max_length=75)),
                ('visual_inspection_skill', models.CharField(blank=True, max_length=75)),
                ('d_height_gauge_operating', models.CharField(blank=True, max_length=75)),
                ('scoring_crieteria', models.CharField(blank=True, max_length=75)),
                ('prepredBy', models.CharField(blank=True, max_length=75)),
                ('approvedBy', models.CharField(blank=True, max_length=75)),
                ('created_On', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='annual_trainnig',
            name='Oct',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='annual_trainnig',
            name='approved_By',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='annual_trainnig',
            name='apr',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='annual_trainnig',
            name='aug',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='annual_trainnig',
            name='dec',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='annual_trainnig',
            name='feb',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='annual_trainnig',
            name='jan',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='annual_trainnig',
            name='jul',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='annual_trainnig',
            name='jun',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='annual_trainnig',
            name='legend',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='annual_trainnig',
            name='mar',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='annual_trainnig',
            name='may',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='annual_trainnig',
            name='nov',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='annual_trainnig',
            name='sep',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
