# Generated by Django 2.2 on 2019-05-10 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cmp_formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CmpName', models.CharField(max_length=100)),
                ('scope', models.TextField(blank=True, null=True)),
                ('policy', models.FilePathField(max_length=300, path=None)),
                ('app_domain', models.URLField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('modify_on', models.DateField(auto_now=True)),
                ('SupUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrgChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desgnations', models.CharField(max_length=100)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('modify_on', models.DateField(auto_now=True)),
                ('CmpName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.Cmp_formation')),
                ('created_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RolesAuthorised',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsiblity', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('modify_on', models.DateField(auto_now=True)),
                ('Authorised', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.OrgChart')),
                ('CmpName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.Cmp_formation')),
                ('created_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrcName', models.CharField(max_length=100)),
                ('CmpName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.Cmp_formation')),
            ],
        ),
    ]
