# Generated by Django 2.2 on 2019-05-23 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmp_formation',
            old_name='policys',
            new_name='policy',
        ),
        migrations.RemoveField(
            model_name='cmp_formation',
            name='scopes',
        ),
    ]
