# Generated by Django 2.2 on 2019-05-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_auto_20190510_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmp_formation',
            name='policy',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
