# Generated by Django 2.2 on 2019-05-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_auto_20190516_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmp_formation',
            name='policy',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
