# Generated by Django 2.2 on 2019-05-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_auto_20190523_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmp_formation',
            name='policy',
            field=models.FileField(blank=True, default='doc/policy.doc', null=True, upload_to='doc/'),
        ),
    ]
