# Generated by Django 2.2 on 2019-05-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0004_auto_20190523_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmp_formation',
            name='policy',
            field=models.FileField(blank=True, default=None, null=True, upload_to='doc/'),
        ),
    ]
