# Generated by Django 2.2 on 2019-05-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0004_auto_20190517_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmp_formation',
            name='policy',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
