# Generated by Django 2.2 on 2019-05-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0005_auto_20190523_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmp_formation',
            name='policy',
            field=models.FileField(blank=True, default='doc/none/no-img.pdf', null=True, upload_to='doc/'),
        ),
    ]
