# Generated by Django 2.2 on 2019-05-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0005_auto_20190517_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmp_formation',
            name='policy',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
