# Generated by Django 2.2 on 2019-05-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0006_auto_20190523_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmp_formation',
            name='policy',
            field=models.FileField(blank=True, null=True, upload_to='doc/'),
        ),
    ]
