# Generated by Django 2.2 on 2019-05-31 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formation', '0007_auto_20190523_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgProcessChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(blank=True, max_length=150, null=True)),
                ('child', models.CharField(max_length=150)),
                ('created_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('orgName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.Cmp_formation')),
            ],
        ),
    ]
