# Generated by Django 2.2 on 2019-05-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0008_orgprocesschart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprocesschart',
            name='parentid',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
