# Generated by Django 2.2 on 2019-05-31 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formation', '0009_orgprocesschart_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgprocesschart',
            name='parentid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='OrgTestprocess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart', models.TextField()),
                ('created_at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('orgName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formation.Cmp_formation')),
            ],
        ),
    ]
