# Generated by Django 2.2 on 2019-08-05 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formation', '0010_auto_20190531_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingMinuts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subTitle', models.TextField(blank=True, null=True)),
                ('post', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('modify_on', models.DateField(auto_now=True)),
                ('created_at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('orgName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formation.Cmp_formation')),
            ],
        ),
    ]
