# Generated by Django 2.2 on 2019-05-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pur_approved_supplier',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Under Evaluation', 'Under Evaluation'), ('Restricted', 'Restricted'), ('Disapproved', 'Disapproved')], default=1, max_length=50),
        ),
    ]
