# Generated by Django 2.2 on 2019-05-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pur', '0002_auto_20190507_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pur_goods_receipt_register',
            name='Hieght',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pur_goods_receipt_register',
            name='accepted_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pur_goods_receipt_register',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='pur_goods_receipt_register',
            name='dc_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pur_goods_receipt_register',
            name='diameter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pur_goods_receipt_register',
            name='grrno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pur_goods_receipt_register',
            name='heat_lot_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pur_goods_receipt_register',
            name='inward_qty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pur_goods_receipt_register',
            name='lenght',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pur_goods_receipt_register',
            name='part',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pur_goods_receipt_register',
            name='po_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pur_goods_receipt_register',
            name='rej_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pur_goods_receipt_register',
            name='return_dc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pur_goods_receipt_register',
            name='sup_test_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pur_goods_receipt_register',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
