# Generated by Django 2.2 on 2019-04-10 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mtk_enquiry_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('proDeliverDate', models.DateField(blank=True)),
                ('contact', models.IntegerField(blank=True)),
                ('contryCode', models.SmallIntegerField(blank=True)),
                ('partNumber', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
                ('drawingNumber', models.CharField(blank=True, max_length=60)),
                ('qty', models.IntegerField(blank=True)),
                ('quotationRef', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('poNumber', models.IntegerField(blank=True)),
                ('creadedOn', models.DateField(auto_now=True, null=True)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='technicall_feasibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_mtrl', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('m_c', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('tools', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('Spl_process', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('any_cad_req', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('out_source', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('creadedOn', models.DateField(auto_now=True, null=True)),
                ('cusomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.mtk_enquiry_register')),
                ('owner', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
