# Generated by Django 2.2 on 2019-06-13 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mtk_enquiry_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('prodeliverDate', models.DateField(blank=True, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('contryCode', models.SmallIntegerField(blank=True, null=True)),
                ('line_number', models.CharField(blank=True, max_length=60)),
                ('partNumber', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
                ('drawingNumber', models.CharField(blank=True, max_length=60)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('quotationRef', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('poNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('creadedOn', models.DateField(auto_now=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tech_feasibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creadedOn', models.DateField(auto_now=True, null=True)),
                ('r_mtrl', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('m_c', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('tools', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('Spl_process', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('any_cad_req', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('out_source', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('cusomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.mtk_enquiry_register')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mkt', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('qcd', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('pur', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('prd', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('creadedOn', models.DateField(auto_now=True, null=True)),
                ('cusomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.mtk_enquiry_register')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='quality_feasibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('gauge', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('can_aql_be_achived', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('is_fai_required', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('key_chare', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('ispection_as_per', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('creadedOn', models.DateField(auto_now=True, null=True)),
                ('cusomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.mtk_enquiry_register')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='marketing_feasibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_statuatory_regulatory', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('is_delivery_feasibility', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('is_nre_applicable', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('creadedOn', models.DateField(auto_now=True, null=True)),
                ('cusomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.mtk_enquiry_register')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='configuration_management_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creadedOn', models.DateField(auto_now=True, null=True)),
                ('customer_order', models.CharField(blank=True, max_length=300)),
                ('route_card_no', models.CharField(blank=True, max_length=100)),
                ('internal_job_order', models.CharField(blank=True, max_length=300)),
                ('rev_no', models.CharField(blank=True, max_length=100)),
                ('invoice_no', models.CharField(blank=True, max_length=100)),
                ('cusomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.mtk_enquiry_register')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
