# Generated by Django 2.2 on 2019-04-10 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mkt', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('qcd', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('pur', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('prd', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('creadedOn', models.DateField(auto_now=True, null=True)),
                ('cusomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.mtk_enquiry_register')),
                ('owner', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='quality_feasibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('gauge', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('can_aql_be_achived', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('is_fai_required', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('key_chare', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('ispection_as_per', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('creadedOn', models.DateField(auto_now=True, null=True)),
                ('cusomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.mtk_enquiry_register')),
                ('owner', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='marketing_feasibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_statuatory_regulatory', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('is_delivery_feasibility', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('is_nre_applicable', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('creadedOn', models.DateField(auto_now=True, null=True)),
                ('cusomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.mtk_enquiry_register')),
                ('owner', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='configuration_management_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creadedOn', models.DateField(auto_now=True, null=True)),
                ('customer_order', models.CharField(blank=True, max_length=300)),
                ('route_card_no', models.CharField(blank=True, max_length=100)),
                ('internal_job_order', models.CharField(blank=True, max_length=300)),
                ('rev_no', models.CharField(blank=True, max_length=100)),
                ('invoice_no', models.CharField(blank=True, max_length=100)),
                ('cusomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.mtk_enquiry_register')),
                ('owner', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
