# Generated by Django 2.2 on 2019-04-17 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20190416_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtk_enquiry_register',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
