# Generated by Django 2.2 on 2019-06-25 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_feasibility_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feasibility_study',
            name='company_capability',
        ),
        migrations.RemoveField(
            model_name='feasibility_study',
            name='customer_requirement',
        ),
        migrations.RemoveField(
            model_name='feasibility_study',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='feasibility_study',
            name='slNo',
        ),
        migrations.CreateModel(
            name='feasibility_study_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slNo', models.FloatField(blank=True, null=True)),
                ('company_capability', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_requirement', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('feasibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.feasibility_study')),
            ],
        ),
    ]
