# Generated by Django 2.2 on 2019-04-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_auto_20190417_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtk_enquiry_register',
            name='owner',
        ),
    ]
