# Generated by Django 2.2 on 2019-04-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_remove_mtk_enquiry_register_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtk_enquiry_register',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='mtk_enquiry_register',
            name='contryCode',
        ),
        migrations.RemoveField(
            model_name='mtk_enquiry_register',
            name='creadedOn',
        ),
        migrations.RemoveField(
            model_name='mtk_enquiry_register',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mtk_enquiry_register',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mtk_enquiry_register',
            name='drawingNumber',
        ),
        migrations.RemoveField(
            model_name='mtk_enquiry_register',
            name='partNumber',
        ),
        migrations.RemoveField(
            model_name='mtk_enquiry_register',
            name='poNumber',
        ),
        migrations.RemoveField(
            model_name='mtk_enquiry_register',
            name='prodeliverDate',
        ),
        migrations.RemoveField(
            model_name='mtk_enquiry_register',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='mtk_enquiry_register',
            name='quotationRef',
        ),
        migrations.RemoveField(
            model_name='mtk_enquiry_register',
            name='status',
        ),
    ]
