# Generated by Django 2.2 on 2019-04-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_auto_20190426_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtk_enquiry_register',
            name='line_number',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
