# Generated by Django 2.2 on 2019-04-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_mtk_enquiry_register_line_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtk_enquiry_register',
            name='poNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mtk_enquiry_register',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
